package com.meetrivo.model;

public enum AnalyticsEventType {
    USER_LOGIN,
    USER_REGISTER,
    MEETING_CREATED,
    MEETING_JOINED,
    MEETING_ENDED,
    CHAT_SENT,
    SCREEN_SHARE_STARTED,
    RECORDING_STARTED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_DOWNGRADED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_RENEWED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REVENUE_GENERATED,
    PUSH_NOTIFICATION_SENT
}
