package com.meetrivo.service;

import com.meetrivo.model.Report;
import com.meetrivo.model.Role;
import com.meetrivo.model.User;
import com.meetrivo.repository.ReportRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class ReportService extends BaseService {

    private final ReportRepository reportRepository;
    private final AnalyticsService analyticsService;

    public Report generateUserReport() {
        validateAdminOrSuperAdmin();
        User actor = getCurrentUser();

        Map<String, Object> data = analyticsService.getUserAnalytics();
        Report report = Report.builder()
                .reportType("USER")
                .title("User Activity and Registrations Report")
                .generatedBy(actor.getEmail())
                .generatedAt(LocalDateTime.now())
                .data(data)
                .build();

        Report saved = reportRepository.save(report);
        logInfo("User Report generated by " + actor.getEmail());
        return saved;
    }

    public Report generateMeetingReport() {
        validateAdminOrSuperAdmin();
        User actor = getCurrentUser();

        Map<String, Object> data = analyticsService.getMeetingAnalytics();
        Report report = Report.builder()
                .reportType("MEETING")
                .title("Meeting Usage and Engagement Report")
                .generatedBy(actor.getEmail())
                .generatedAt(LocalDateTime.now())
                .data(data)
                .build();

        Report saved = reportRepository.save(report);
        logInfo("Meeting Report generated by " + actor.getEmail());
        return saved;
    }

    public Report generateSystemReport() {
        validateAdminOrSuperAdmin();
        User actor = getCurrentUser();

        Map<String, Object> data = analyticsService.getSystemAnalytics();
        Report report = Report.builder()
                .reportType("SYSTEM")
                .title("Complete Platform Performance Report")
                .generatedBy(actor.getEmail())
                .generatedAt(LocalDateTime.now())
                .data(data)
                .build();

        Report saved = reportRepository.save(report);
        logInfo("System Report generated by " + actor.getEmail());
        return saved;
    }

    // ─── Export Utilities ────────────────────────────────────────────────────

    public String exportToCsv(String reportId) {
        validateAdminOrSuperAdmin();
        Report report = reportRepository.findById(reportId)
                .orElseThrow(() -> new RuntimeException("Report not found: " + reportId));

        StringBuilder csv = new StringBuilder();
        csv.append("Report Title: ").append(report.getTitle()).append("\n");
        csv.append("Generated By: ").append(report.getGeneratedBy()).append("\n");
        csv.append("Generated At: ").append(report.getGeneratedAt()).append("\n\n");
        csv.append("Metric,Value\n");

        if (report.getData() != null) {
            for (Map.Entry<String, Object> entry : report.getData().entrySet()) {
                csv.append(entry.getKey()).append(",").append(entry.getValue()).append("\n");
            }
        }
        return csv.toString();
    }

    public String exportToExcel(String reportId) {
        validateAdminOrSuperAdmin();
        Report report = reportRepository.findById(reportId)
                .orElseThrow(() -> new RuntimeException("Report not found: " + reportId));

        StringBuilder excelXml = new StringBuilder();
        excelXml.append("<?xml version=\"1.0\"?>\n");
        excelXml.append("<Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\">\n");
        excelXml.append(" <Worksheet Name=\"Report\">\n");
        excelXml.append("  <Table>\n");
        excelXml.append("   <Row><Cell><Data Type=\"String\">Report Title: ").append(report.getTitle()).append("</Data></Cell></Row>\n");
        excelXml.append("   <Row><Cell><Data Type=\"String\">Generated At: ").append(report.getGeneratedAt()).append("</Data></Cell></Row>\n");
        excelXml.append("   <Row>\n");
        excelXml.append("    <Cell><Data Type=\"String\">Metric</Data></Cell>\n");
        excelXml.append("    <Cell><Data Type=\"String\">Value</Data></Cell>\n");
        excelXml.append("   </Row>\n");

        if (report.getData() != null) {
            for (Map.Entry<String, Object> entry : report.getData().entrySet()) {
                excelXml.append("   <Row>\n");
                excelXml.append("    <Cell><Data Type=\"String\">").append(entry.getKey()).append("</Data></Cell>\n");
                excelXml.append("    <Cell><Data Type=\"String\">").append(entry.getValue()).append("</Data></Cell>\n");
                excelXml.append("   </Row>\n");
            }
        }

        excelXml.append("  </Table>\n");
        excelXml.append(" </Worksheet>\n");
        excelXml.append("</Workbook>\n");

        return excelXml.toString();
    }

    public Map<String, Object> getPdfReadyStructure(String reportId) {
        validateAdminOrSuperAdmin();
        Report report = reportRepository.findById(reportId)
                .orElseThrow(() -> new RuntimeException("Report not found: " + reportId));

        Map<String, Object> pdfStructure = new HashMap<>();
        pdfStructure.put("documentTitle", report.getTitle());
        pdfStructure.put("author", report.getGeneratedBy());
        pdfStructure.put("date", report.getGeneratedAt().toString());
        pdfStructure.put("pageOrientation", "PORTRAIT");
        pdfStructure.put("tableHeaders", List.of("Metric", "Value"));
        pdfStructure.put("rows", report.getData());

        return pdfStructure;
    }

    private User getCurrentUser() {
        return (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
    }

    private void validateAdminOrSuperAdmin() {
        User user = getCurrentUser();
        if (user.getRole() != Role.ADMIN && user.getRole() != Role.SUPER_ADMIN) {
            throw new RuntimeException("Access Denied: Admin or Super Admin role required");
        }
    }
}
