apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meetrivo-recordings-pvc
  namespace: meetrivo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
