apiVersion: v1
kind: Secret
metadata:
  name: meetrivo-secrets
  namespace: meetrivo
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb-service:27017/meetrivo"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  STORAGE_PATH: "/app/recordings"
