package com.meetrivo.websocket;

public enum MeetingEventType {
    USER_JOINED,
    USER_LEFT,
    HOST_JOINED,
    HOST_LEFT,
    MEETING_STARTED,
    MEETING_ENDED,
    PARTICIPANT_MUTED,
    PARTICIPANT_UNMUTED,
    SCREEN_SHARE_STARTED,
    SCREEN_SHARE_STOPPED
}
